### PR TITLE
Use CSS modules

### LINKED ISSUE #12: Use CSS modules
Not sure why this isn't the default

### PR DESCRIPTION
**Pull request by andrewrubin**
# Goal
Convert the styling of this package to use CSS modules, so that we have "scoped" selectors.

## What was added?
- CSS modules to Vite config
- Bump to v4.0.0, as this is a breaking change

## What was removed or fixed?
- Removed the onClick prop from `<GalleryPaginationItem>`. In retrospect this felt unneccessary, for two reasons:
  - The gallery provides an `onChange` callback you can use
  - GalleryPaginationItem allows you to pass `buttonProps`, so you could re-create this behavior using that and the Gallery hook, if you absolutely needed to.
- Adjusted development demo styling to accommodate new CSS module change

## Screenshots
gallery

## Does this close any open issues?
Closes #12

### CODE REVIEW

**Review by liamegan — APPROVED** [review]
LGTM

**Review by marlonmarcello — APPROVED** [review]

**Comment by marlonmarcello** [comment]
@andrewrubin just gotta rebase main and it should be ready to go

**Comment by andrewrubin** [comment]
Hey @NicholasLancey , @rvno , and @chanroyc, would love to get this one merged if you have 5 mins to look at it today! Thanks

**Review by NicholasLancey — APPROVED** [review]
Nice one @andrewrubin, looks good to me!

**Pull request merged**
